"use client";
import {useState} from "react";
const bars=[10,24,38,17,49,29,14,42,33,51,21,37,13,27,45];
function InspectionPlate(){return <aside className="inspection" aria-label="Exemplo de ajuda do Vistorino"><div className="plate-top"><span>VISTORINO</span><b>TE AJUDANDO</b></div><div className="plate-model"><p>CARRO QUE VOCÊ ESTÁ OLHANDO</p><strong>Honda Civic</strong><span>2015 · 2.0 FLEX · PRATA</span></div><div className="audio"><button aria-label="Reproduzir exemplo">▶</button><div className="bars">{bars.map((h,i)=><i key={i} style={{height:h}}/>)}</div><small>00:18</small></div><div className="plate-rule"/><div className="plate-label"><span>COISAS PRA VOCÊ CONFERIR</span><b>03</b></div><ol><li><em>01</em><span>Kit correia dentada</span><b>OLHA ISSO</b></li><li><em>02</em><span>Bomba d&apos;água</span><b>PERGUNTA</b></li><li><em>03</em><span>Tensor da correia</span><b>CONFERE</b></li></ol><div className="plate-foot"><span>ENTENDI O SEU ÁUDIO</span><span>✓</span></div></aside>}
function Phone(){return <div className="phone" aria-label="Demonstração ilustrativa do WhatsApp"><div className="phone-notch"/><header><i>‹</i><b>V</b><div><strong>Vistorino</strong><small>seu amigo que entende de carro</small></div><span>•••</span></header><div className="messages"><p className="date">HOJE</p><div className="bubble bot">Me manda um áudio e me conta o que você achou estranho no carro.</div><div className="bubble user">É um Civic 2015. Ouvi um barulho na correia e o mecânico falou da bomba d&apos;água.</div><div className="bubble bot result-msg"><span>✓</span> Boa. Separei 3 coisas pra você perguntar antes de fechar negócio.<small>ver o que eu encontrei →</small></div></div><footer>＋　Mensagem　　　　　　　　　⌁</footer></div>}
export default function Home(){const [open,setOpen]=useState(false);return <main><nav className="nav"><a className="logo" href="#top"><span>V</span>VISTORINO</a><button className="mobile" onClick={()=>setOpen(!open)} aria-label="Abrir menu" aria-expanded={open}>☰</button><div className={open?"links show":"links"}><a href="#processo">Como funciona</a><a href="#na-pratica">Na prática</a><a className="nav-button" href="#contato">Falar com o Vistorino <b>↗</b></a></div></nav>
<section className="hero" id="top"><div className="hero-photo"><div className="photo-copy"><p><i/> SEU AMIGO PRA OLHAR CARRO USADO</p><h1>Mandou o áudio?<br/><em>Deixa comigo.</em></h1><div className="hero-rail"><span>01</span><b>Você conta o que viu.<br/>O Vistorino te ajuda a entender.</b></div></div><div className="speed-lines"/></div><div className="hero-panel"><p className="kicker">UM AMIGO QUE ENTENDE O QUE VOCÊ OUVIU NO CARRO</p><h2>Fala comigo<br/>antes de <em>fechar.</em></h2><p className="intro">Achou um barulho estranho? Ficou com dúvida depois da avaliação? Manda um áudio no WhatsApp. O Vistorino organiza a conversa e te ajuda a saber o que perguntar.</p><a href="#contato" className="action">Quero falar com ele <span>→</span></a><div className="panel-detail"><i>⌁</i><span>VOCÊ MANDA O ÁUDIO<br/><b>O VISTORINO TE AJUDA</b></span></div></div><div className="hero-plate"><InspectionPlate/></div></section>
<section className="cred"><div><b>FALAR</b><span>→</span><b>IDENTIFICAR</b><span>→</span><b>CONFERIR</b><span>→</span><b>NEGOCIAR</b><span>→</span></div></section>
<section className="process wrap" id="processo"><div className="section-heading"><p className="kicker"><i/> VOCÊ CONTA. ELE TE AJUDA A ORGANIZAR.</p><h2>Não precisa falar<br/><em>“mecaniquês”.</em></h2><p>Fala do seu jeito. O Vistorino entende o contexto e te devolve uma conversa mais clara para você decidir.</p></div><div className="checks"><article><span className="check-number">A</span><div className="check-icon audio-icon">⌁</div><h3>Manda um áudio</h3><p>Conta o que te deixou com a pulga atrás da orelha.</p><small>“OUVI UM BARULHO...”</small></article><article><span className="check-number">B</span><div className="check-icon car-icon">▰</div><h3>Ele puxa assunto</h3><p>Se faltar algo, ele pergunta sobre o modelo e o que você viu.</p><small>“QUAL O ANO DELE?”</small></article><article><span className="check-number">C</span><div className="check-icon list-icon">≡</div><h3>Vocês entendem juntos</h3><p>Você recebe pontos claros para conferir e perguntar sem vergonha.</p><small>“OLHA ISSO AQUI”</small></article></div></section>
<section className="evidence" id="na-pratica"><div className="evidence-copy"><p className="kicker light"><i/> AQUELA DÚVIDA NÃO FICA SÓ NA SUA CABEÇA</p><h2>Você fala.<br/><em>Ele clareia.</em></h2><p>O Vistorino pega o que você contou e deixa visível o que vale conferir. É como mandar áudio para aquele amigo que entende de carro.</p><div className="metric"><b>03</b><span>coisas pra perguntar<br/>neste exemplo</span></div></div><Phone/><div className="tire-mark">V</div></section>
<section className="decision wrap"><div><p className="kicker"><i/> PRA QUEM GOSTA DE ENTENDER ANTES DE COMPRAR</p><h2>Não precisa saber<br/>tudo de carro.<br/>Pode só <em>perguntar.</em></h2></div><div className="decision-card"><span>V</span><p>Um amigo no WhatsApp para te ajudar a entender melhor o carro que você está olhando.</p><a href="#contato">Conheça o Vistorino <b>↗</b></a></div></section>
<footer id="contato"><div className="footer-main"><a className="logo" href="#top"><span>V</span>VISTORINO</a><h2>Manda o áudio.<br/>Ele te ajuda.</h2><a className="footer-action" href="mailto:oi@vistorino.com">Fale com o Vistorino <b>↗</b></a></div><div className="footer-bottom"><span>© 2026 Vistorino</span><span>Seu amigo pra olhar carro usado.</span><a href="#top">Voltar ao topo ↑</a></div></footer></main>}
