"use client";
import {useState} from "react";
const bars=[10,24,38,17,49,29,14,42,33,51,21,37,13,27,45];
function InspectionPlate(){return <aside className="inspection" aria-label="Exemplo de ajuda do Vistorino"><div className="plate-top"><span>VISTORINO</span><b>TE AJUDANDO</b></div><div className="plate-model"><p>CARRO QUE VOCÊ ESTÁ OLHANDO</p><strong>Honda Civic</strong><span>2015 · 2.0 FLEX · PRATA</span></div><div className="audio"><button aria-label="Reproduzir exemplo">▶</button><div className="bars">{bars.map((h,i)=><i key={i} style={{height:h}}/>)}</div><small>00:18</small></div><div className="plate-rule"/><div className="plate-label"><span>COISAS PRA VOCÊ CONFERIR</span><b>03</b></div><ol><li><em>01</em><span>Kit correia dentada</span><b>OLHA ISSO</b></li><li><em>02</em><span>Bomba d&apos;água</span><b>PERGUNTA</b></li><li><em>03</em><span>Tensor da correia</span><b>CONFERE</b></li></ol><div className="plate-foot"><span>ENTENDI O SEU ÁUDIO</span><span>✓</span></div></aside>}
function Phone(){return <div className="phone" aria-label="Demonstração ilustrativa da resposta do Vistorino no WhatsApp"><div className="phone-notch"/><header><i>‹</i><b>V</b><div><strong>Vistorino</strong><small>seu amigo que entende de carro</small></div><span>•••</span></header><div className="messages"><p className="date">HOJE</p><div className="bubble bot">Me manda um áudio e me conta o que você achou estranho no carro.</div><div className="bubble user audio-bubble"><span className="audio-play">▶</span><div className="audio-wave">{bars.slice(0,12).map((h,i)=><i key={i} style={{height:h/2}}/>)}</div><b>0:18</b><small>10:42 ✓✓</small></div><div className="bubble bot result-msg"><span>✓</span> Encontrei 3 peças pra você pesquisar:</div><div className="parts-message"><p>Honda Civic 2015</p><a href="https://www.google.com/search?q=kit+correia+dentada+honda+civic+2015" target="_blank" rel="noreferrer"><span>Kit correia dentada</span><b>R$ 245</b><em>Pesquisar ↗</em></a><a href="https://www.google.com/search?q=bomba+d%27agua+honda+civic+2015" target="_blank" rel="noreferrer"><span>Bomba d&apos;água</span><b>R$ 189</b><em>Pesquisar ↗</em></a><a href="https://www.google.com/search?q=tensor+correia+honda+civic+2015" target="_blank" rel="noreferrer"><span>Tensor da correia</span><b>R$ 132</b><em>Pesquisar ↗</em></a><footer><span>Total das peças</span><b>R$ 566</b><small>valores de exemplo</small></footer></div></div><footer>＋　Mensagem　　　　　　　　　⌁</footer></div>}
export default function Home(){const [open,setOpen]=useState(false);return <main><nav className="nav"><a className="logo" href="#top"><span>V</span>VISTORINO</a><button className="mobile" onClick={()=>setOpen(!open)} aria-label="Abrir menu" aria-expanded={open}>☰</button><div className={open?"links show":"links"}><a href="#processo">Como funciona</a><a href="#na-pratica">Na prática</a><a className="nav-button" href="#contato">Falar com o Vistorino <b>↗</b></a></div></nav>
 <section className="hero" id="top"><div className="hero-photo"><div className="photo-copy"><p><i/> SEU AMIGO PRA OLHAR CARRO USADO</p><h1>Mandou o áudio?<br/><em>Deixa comigo.</em></h1><p className="hero-intro">Você conta o que viu. O Vistorino te ajuda a entender o que vale perguntar antes de fechar.</p><a href="#processo" className="action">Entenda como funciona <span>→</span></a></div><div className="speed-lines"/></div><div className="hero-panel"><p className="kicker">A CONVERSA ACONTECE NO WHATSAPP</p><Phone/><small className="phone-caption">simulação da conversa · valores ilustrativos</small></div></section>
<section className="cred"><div><b>FALAR</b><span>→</span><b>IDENTIFICAR</b><span>→</span><b>CONFERIR</b><span>→</span><b>NEGOCIAR</b><span>→</span></div></section>
<section className="process wrap" id="processo"><div className="section-heading"><p className="kicker"><i/> VOCÊ CONTA. ELE TE AJUDA A ORGANIZAR.</p><h2>Não precisa falar<br/><em>“mecaniquês”.</em></h2><p>Fala do seu jeito. O Vistorino entende o contexto e te devolve uma conversa mais clara para você decidir.</p></div><div className="checks"><article><span className="check-number">A</span><div className="check-icon audio-icon">⌁</div><h3>Manda um áudio</h3><p>Conta o que te deixou com a pulga atrás da orelha.</p><small>“OUVI UM BARULHO...”</small></article><article><span className="check-number">B</span><div className="check-icon car-icon">▰</div><h3>Ele puxa assunto</h3><p>Se faltar algo, ele pergunta sobre o modelo e o que você viu.</p><small>“QUAL O ANO DELE?”</small></article><article><span className="check-number">C</span><div className="check-icon list-icon">≡</div><h3>Vocês entendem juntos</h3><p>Você recebe pontos claros para conferir e perguntar sem vergonha.</p><small>“OLHA ISSO AQUI”</small></article></div></section>
<footer id="contato"><div className="footer-main"><a className="logo" href="#top"><span>V</span>VISTORINO</a><h2>Manda o áudio.<br/>Ele te ajuda.</h2><a className="footer-action" href="mailto:oi@vistorino.com">Fale com o Vistorino <b>↗</b></a></div><div className="footer-bottom"><span>© 2026 Vistorino</span><span>Seu amigo pra olhar carro usado.</span><a href="#top">Voltar ao topo ↑</a></div></footer></main>}
